#!/bin/sh
#
# Trigger serial bootup sequence for K1 MCU.
#

PID_FILE=/run/klipper_mcu.pid

start() {
    printf "Starting klipper host mcu: "
    start-stop-daemon -S -b -m -p $PID_FILE --exec /usr/bin/klipper_mcu -- -r
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
    if [ -c /tmp/klipper_host_mcu ]; then
	echo "FORCE_SHUTDOWN" > /tmp/klipper_host_mcu 2> /dev/null
    fi
    
    printf "Stopping klipper host mcu: "
    start-stop-daemon -K -q -p $PID_FILE
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
  	restart
	;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
