#!/bin/sh
#
# Trigger serial bootup sequence for K1 MCU.
#

start() {
    #### TODO fix me for K1
}

case "$1" in
  start)
        start
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
